name: LeafGrapple
version: 1.0.2
main: me.LeafPixel.leafgrapple.LeafGrapplePlugin
api-version: '1.21'
folia-supported: true

author: LeafPixel
description: A safe Paper/Folia grappling hook plugin.

commands:
  leafgrapple:
    description: Main command of LeafGrapple.
    usage: /leafgrapple
    aliases:
      - grapple
      - lg

permissions:
  leafgrapple.admin:
    description: Allows using admin commands of LeafGrapple.
    default: op
  leafgrapple.entityhook.bypass:
    description: Prevents the player from being hooked by entity grapple.
    default: false